export const SKINS = [
  {
    id: 'classic',
    name: 'CLASSIC',
    blurb: 'The original golden-brown hero.',
    crust: '#c4843d',
    crumb: '#f6d7a2',
    accent: '#e7b56a',
    cheek: '#efb08a',
    mouth: '#6a3418',
  },
  {
    id: 'strawberry',
    name: 'STRAWBERRY',
    blurb: 'Seed-speckled and jammy.',
    crust: '#d83b5c',
    crumb: '#ff9bb6',
    accent: '#ffd0dc',
    cheek: '#ff7f9f',
    mouth: '#7a1438',
    extra: 'seeds',
  },
  {
    id: 'blueberry',
    name: 'BLUEBERRY',
    blurb: 'A cool berry batch.',
    crust: '#3a2c86',
    crumb: '#7d6ae0',
    accent: '#c7b6ff',
    cheek: '#9a86f0',
    mouth: '#241456',
    extra: 'berries',
  },
  {
    id: 'galaxy',
    name: 'GALAXY',
    blurb: 'Toasted somewhere past orbit.',
    crust: '#2a1648',
    crumb: '#3d2d86',
    accent: '#86fff3',
    cheek: '#6a4ad4',
    mouth: '#d7c6ff',
    extra: 'stars',
  },
  {
    id: 'avocado',
    name: 'AVOCADO',
    blurb: 'Green, creamy, and a little extra.',
    crust: '#2f6a34',
    crumb: '#c6e07a',
    accent: '#6b3e22',
    cheek: '#e7c39a',
    mouth: '#245028',
    extra: 'pit',
  },
  {
    id: 'butter',
    name: 'BUTTER',
    blurb: 'Melted, glossy, and ready.',
    crust: '#e2a122',
    crumb: '#ffe38a',
    accent: '#fff6cf',
    cheek: '#ffd27a',
    mouth: '#8a5a10',
    extra: 'butter',
  },
  {
    id: 'legendary',
    name: 'LEGENDARY TOAST',
    blurb: 'A crowned toast with a shield.',
    crust: '#f0c53a',
    crumb: '#fff3c4',
    accent: '#fff8dc',
    cheek: '#ffd98a',
    mouth: '#7a4a08',
    extra: 'legendary',
    cost: 50,
    power: {
      id: 'block',
      button: 'BLOCK',
      hold: true,
      keys: 'HOLD SHIFT TO BLOCK',
      touch: 'HOLD BLOCK TO BLOCK',
      hintKeys: 'SHIFT block',
      hintTouch: 'hold BLOCK',
      detail: 'Shrugs off hits and shoves nearby toasts away.',
    },
  },
  {
    id: 'inferno',
    name: 'INFERNO TOAST',
    blurb: 'A crust still on fire.',
    crust: '#8a2412',
    crumb: '#ff7a32',
    accent: '#ffd15a',
    cheek: '#ff5a3a',
    mouth: '#4a1008',
    extra: 'inferno',
    cost: 80,
    power: {
      id: 'burn',
      button: 'BURN',
      hold: true,
      keys: 'HOLD SHIFT TO BURN',
      touch: 'HOLD BURN TO SCORCH',
      hintKeys: 'SHIFT burn',
      hintTouch: 'hold BURN',
      detail: 'Scorches toasts standing in front of you.',
    },
  },
  {
    id: 'frost',
    name: 'FROST TOAST',
    blurb: 'Cold enough to slow a fight.',
    crust: '#1d4e86',
    crumb: '#d7f4ff',
    accent: '#8ee7ff',
    cheek: '#9fd4ff',
    mouth: '#123056',
    extra: 'frost',
    cost: 70,
    power: {
      id: 'freeze',
      button: 'FROST',
      hold: true,
      keys: 'HOLD SHIFT TO FREEZE',
      touch: 'HOLD FROST TO CHILL',
      hintKeys: 'SHIFT freeze',
      hintTouch: 'hold FROST',
      detail: 'Slows nearby toasts so they can barely move.',
    },
  },
  {
    id: 'phantom',
    name: 'PHANTOM TOAST',
    blurb: 'Here, then somewhere else.',
    crust: '#3a245c',
    crumb: '#c9b6ff',
    accent: '#f2e9ff',
    cheek: '#b89cff',
    mouth: '#2a1848',
    extra: 'phantom',
    cost: 110,
    power: {
      id: 'dash',
      button: 'DASH',
      hold: false,
      keys: 'TAP SHIFT TO DASH',
      touch: 'TAP DASH TO BLINK',
      hintKeys: 'SHIFT dash',
      hintTouch: 'tap DASH',
      detail: 'Blinks forward, slips past a hit, and bonks anything in the way.',
    },
  },
];

export function getSkin(id) {
  return SKINS.find((skin) => skin.id === id) || SKINS[0];
}

export const ENEMY_SKIN = {
  id: 'enemy',
  name: 'ENEMY',
  crust: '#a33b22',
  crumb: '#e7b08a',
  accent: '#ff6a3d',
  cheek: '#ff7a62',
  mouth: '#4a120c',
};
